apiVersion: v1
kind: Pod
metadata:
  name: testpod
  namespace: default
  labels:
    run: testpod
spec:
  containers:
  - name: testpod
    image: busybox
    imagePullPolicy: Always
    args:
    - sleep
    - infinity